### PR TITLE
refactor: slimming down the size of our unicode dump by removing unneeded data

### PR DESCRIPTION
**Pull request by erunion**
This makes some drastic reductions to the size of our emoji Unicode dump (by way of [gemoji](https://www.npmjs.com/package/gemoji)) by removing data that we aren't actually using within the [EmojiPicker](https://github.com/readmeio/ui/blob/next/src/ui/components/EmojiPicker/index.js#L32-L49).

Since we actually utilize `emoji`, `aliases`, and `ios_version` there it doesn't make sense for us to ship a JSON dump of unnecessary that tops out at ~400KB.

With these reductions `unicode/index.json` caps out at 120KB, an almost 60% drop in size.

### CODE REVIEW

**Review by rafegoldberg — APPROVED** [review]
Fast moves here; this looks good to me.

**Review by domharrington — APPROVED** [review]
Amazing thank you! Wonder how other people do this... 

Seems like this module has a similar problem too: https://github.com/ealush/emoji-picker-react/blob/master/src/emojis.json

Happy with this, but will be good when we can *only* include this on the Tutorials page.

**Comment by domharrington** [comment]
Wonder how much smaller we could make it by replacing "emoji", "aliases" and "ios_version" in the json with smaller keys.

**Comment by erunion** [comment]
Made another change to store the emoijs as an array of arrays:

```
[["😀",["grinning"]],["😃",["smiley"]], ...]
```

Bundle is now 44k.

**Pull request merged**
